services:
  postgres:
    container_name: odoo-postgres
    image: postgres:17-alpine
    networks:
      - web
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  odoo:
    container_name: odoo
    image: odoo:18.0
    networks:
      - web
    environment:
      - HOST: ${HOST}
      - USER: ${USER}
      - PASSWORD: ${PASSWORD}
    depends_on:
      - postgres
    ports:
      - 8069:8069
    volumes:
      - config:/etc/odoo
      - extra-addons:/mnt/extra-addons
      - data:/var/lib/odoo
    restart: always
    links:
      - postgres

volumes:
  postgres-data:
  config:
  extra-addons:
  data:

networks:
  web:
    external: true
    name: web